
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
// import { Provider } from "react-redux";
// import { store } from "./redux/store";

import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Providers } from "../redux/Provider";
import BackToTop from "../components/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Search Architect",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo/company-logo.webp", // or '/favicon.svg'
  },
};

export default function RootLayout({ children }) {
  return (
  
     <>
       <Toaster/>
          <GoogleOAuthProvider clientId={process.env.NEXT_OAUTH_CLIENT_ID}>
            <Providers  >
      {/* <Preloader /> */}
      {/* <RouteChangeLoader /> */}
            {children}
            <BackToTop/>
            </Providers>
          </GoogleOAuthProvider>
     </>
          
          
   
  );
}
