import SubCategories from '@/app/web-pages/SubCategories'
import React from 'react'
const products = [
    // Exterior Products
    {
        id: "E001",
        name: "Exterior Wall Cladding",
        description: "Weather-resistant cladding for a stylish facade.",
        price: 1599,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E002",
        name: "Roof Shingles",
        description: "Durable and aesthetic roofing solution.",
        price: 1399,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E003",
        name: "Facade Panels",
        description: "Modern facade panels for sleek architecture.",
        price: 1899,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E004",
        name: "Stone Veneers",
        description: "Natural look stone finish for outdoor walls.",
        price: 1749,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E005",
        name: "Wooden Decking",
        description: "Smooth outdoor flooring with hardwood finish.",
        price: 1299,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E006",
        name: "Pergolas",
        description: "Elegant shaded structures for gardens or patios.",
        price: 2499,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E007",
        name: "Garden Fencing",
        description: "Secure and stylish boundaries for your garden.",
        price: 899,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E008",
        name: "Exterior Paint",
        description: "Weatherproof paint to protect and enhance walls.",
        price: 699,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E009",
        name: "Metal Railings",
        description: "Durable railings for balconies and staircases.",
        price: 1099,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E010",
        name: "Outdoor Tiles",
        description: "Anti-slip and durable tiles for exteriors.",
        price: 999,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E011",
        name: "Concrete Pavers",
        description: "Heavy-duty paving blocks for walkways.",
        price: 1149,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E012",
        name: "Louver Panels",
        description: "Ventilated and decorative panels for airflow.",
        price: 1349,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E013",
        name: "Acrylic Sheets",
        description: "Transparent, weatherproof sheets for roofing.",
        price: 1199,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E014",
        name: "Exterior Lighting",
        description: "Highlight architectural features with LED lights.",
        price: 799,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E015",
        name: "Synthetic Turf",
        description: "Low-maintenance green cover for lawns.",
        price: 949,
        image: "/categories-banner/products-categories/exterior.jpg",
    },
    {
        id: "E016",
        name: "Canopies & Awnings",
        description: "Functional coverings for sun and rain protection.",
        price: 1599,
        image: "/categories-banner/products-categories/exterior.jpg",
    },

    // Flooring Products
    {
        id: "F001",
        name: "Wooden Flooring",
        description: "Elegant and durable wooden planks for classic interiors.",
        price: 1299,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F002",
        name: "Ceramic Tiles",
        description: "High-quality ceramic tiles ideal for walls and floors.",
        price: 899,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F003",
        name: "Vinyl Flooring",
        description: "Affordable, water-resistant and easy to install.",
        price: 749,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F004",
        name: "Marble Flooring",
        description: "Luxurious marble with natural veins and shine.",
        price: 1999,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F005",
        name: "Laminate Flooring",
        description: "Stylish and cost-effective alternative to wood.",
        price: 999,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F006",
        name: "Granite Flooring",
        description: "Strong and sleek granite for heavy-duty use.",
        price: 1799,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F007",
        name: "Porcelain Tiles",
        description: "Dense, stain-resistant tiles for modern spaces.",
        price: 1099,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F008",
        name: "Engineered Wood Flooring",
        description: "Real wood veneer layered for stability and beauty.",
        price: 1499,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F009",
        name: "Terracotta Tiles",
        description: "Rustic charm with natural clay finish.",
        price: 899,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F010",
        name: "Mosaic Flooring",
        description: "Artistic small tiles to create vibrant patterns.",
        price: 1299,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F011",
        name: "Concrete Flooring",
        description: "Minimalist industrial style with smooth finish.",
        price: 999,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F012",
        name: "Bamboo Flooring",
        description: "Eco-friendly and durable alternative to hardwood.",
        price: 1399,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F013",
        name: "Travertine Tiles",
        description: "Textured, earthy tiles for a natural stone look.",
        price: 1599,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F014",
        name: "Carpet Tiles",
        description: "Soft and modular carpet squares for custom layouts.",
        price: 899,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F015",
        name: "Slate Flooring",
        description: "Rugged and rich colored natural stone option.",
        price: 1699,
        image: "/categories-banner/products-categories/flooring.jpg",
    },
    {
        id: "F016",
        name: "Resin Flooring",
        description: "Seamless, chemical-resistant surface for industrial use.",
        price: 1499,
        image: "/categories-banner/products-categories/flooring.jpg",
    },

    // Wallpaper Products
    {
        id: "W001",
        name: "Floral Wallpaper",
        description: "Elegant floral patterns to brighten up any room.",
        price: 799,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W002",
        name: "Geometric Wallpaper",
        description: "Bold shapes and lines for a modern look.",
        price: 899,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W003",
        name: "Textured Wallpaper",
        description: "Add depth with realistic textures and layers.",
        price: 999,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W004",
        name: "Vintage Wallpaper",
        description: "Timeless designs inspired by classic interiors.",
        price: 849,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W005",
        name: "Metallic Wallpaper",
        description: "Shimmering surfaces to glam up your walls.",
        price: 1199,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W006",
        name: "3D Effect Wallpaper",
        description: "Create illusion and depth with 3D patterns.",
        price: 1299,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W007",
        name: "Nature Wallpaper",
        description: "Scenic landscapes and botanicals for tranquility.",
        price: 899,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W008",
        name: "Brick Effect Wallpaper",
        description: "Urban style with realistic brick visuals.",
        price: 949,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W009",
        name: "Abstract Wallpaper",
        description: "Creative designs to energize modern spaces.",
        price: 1049,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W010",
        name: "Children's Wallpaper",
        description: "Playful themes and vibrant colors for kids' rooms.",
        price: 749,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W011",
        name: "Damask Wallpaper",
        description: "Classic damask prints for luxury interiors.",
        price: 1099,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W012",
        name: "Marble Look Wallpaper",
        description: "Elegant marble visuals without the weight.",
        price: 999,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W013",
        name: "Wood Panel Wallpaper",
        description: "Natural wood texture without carpentry.",
        price: 949,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W014",
        name: "Tropical Wallpaper",
        description: "Bold leaves and exotic patterns for vibrance.",
        price: 899,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W015",
        name: "Minimalist Wallpaper",
        description: "Subtle designs for modern and calm aesthetics.",
        price: 849,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
    {
        id: "W016",
        name: "Boho Wallpaper",
        description: "Free-spirited patterns for artistic souls.",
        price: 949,
        image: "/categories-banner/products-categories/wallpapers.jpg",
    },
];
const page = () => {
  return (
    <div>
         <SubCategories products={products}/>
    </div>
  )
}

export default page
